### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by spectejb** [chrisdickinson/cssauron#13]
Can you please identify this project's license? Thank you!

**Comment by spectejb** [comment]
I wanted to follow up on my question.  I found this: https://github.com/chrisdickinson/cssauron/blob/ae57ae70c65961457f1f7481d945ed47dfdd2f20/package.json but wanted to confirm that this is MIT licensed.  Any help is greatly appreciated!

**Comment by PLPSDev** [comment]
#12  
Would it be at all possible to approve this pull request to add the appropriate License file?
A license file being present in the source repo is often necessary for companies to approve the usage of node packages. This is the case for myself

**Comment by chrisdickinson** [comment]
Yep – sorry for the trouble. MIT license file added thanks to #12.
